# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QWidget, QDesktopWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import os


class Ui_MainWindow(object):
    def resource_path(self, relative_path):
        """ Get absolute path to resource, works for dev and for PyInstaller """

        base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
        return os.path.join(base_path, relative_path)

    def __init__(self):
        self.times = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 250)
        MainWindow.setWindowIcon(QtGui.QIcon(self.resource_path('clock.jpg')))
        self.model = QtGui.QStandardItemModel()
        self.MW = MainWindow
        self.t = ""
        self.font1 = QtGui.QFont()
        self.font1.setFamily(u"a시월구일굴림2")
        self.font1.setPointSize(15)
        self.font1.setBold(True)
        self.dialog = QtWidgets.QDialog()
        self.dialog.resize(400, 1100)
        self.dialog.setWindowOpacity(1)
        self.dialog.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint | QtCore.Qt.FramelessWindowHint)
        self.dialog.setStyleSheet("background-color: #6F56AA;")
        self.btn1 = QtWidgets.QPushButton(MainWindow)
        self.btn1.setGeometry(QtCore.QRect(410, 210, 81, 31))
        self.btn1.setObjectName("btn1")
        self.timeview = QtWidgets.QListView(MainWindow)
        self.timeview.setGeometry(QtCore.QRect(10, 10, 256, 231))
        self.timeview.setObjectName("timeview")
        self.name = QtWidgets.QLineEdit(MainWindow)
        self.name.setGeometry(QtCore.QRect(342, 60, 131, 20))
        self.name.setObjectName("name")
        self.lbl1 = QtWidgets.QLabel(MainWindow)
        self.lbl1.setGeometry(QtCore.QRect(285, 61, 71, 21))
        self.lbl1.setObjectName("lbl1")
        self.reg = QtWidgets.QPushButton(MainWindow)
        self.reg.setGeometry(QtCore.QRect(390, 22, 81, 31))
        self.reg.setObjectName("reg")
        self.lbl2 = QtWidgets.QLabel(MainWindow)
        self.lbl2.setGeometry(QtCore.QRect(285, 90, 71, 21))
        self.lbl2.setObjectName("lbl2")
        self.modalBtn = QtWidgets.QCommandLinkButton(MainWindow)
        self.modalBtn.setGeometry(QtCore.QRect(290, 140, 185, 41))
        self.modalBtn.setObjectName("modalBtn")
        self.time = QtWidgets.QLineEdit(MainWindow)
        self.time.setGeometry(QtCore.QRect(342, 90, 131, 20))
        self.time.setObjectName("time")
        self.time.setPlaceholderText("미 입력시 현재 시간으로 입력됩니다.")
        self.savBtn = QtWidgets.QPushButton(MainWindow)
        self.savBtn.setObjectName(u"savBtn")
        self.savBtn.setGeometry(QtCore.QRect(310, 210, 81, 31))
        self.spinBox = QtWidgets.QSpinBox(MainWindow)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QtCore.QRect(291, 22, 81, 31))
        self.spinBox.setMinimum(300)
        self.spinBox.setMaximum(500)


        self.retranslateUi(MainWindow)
        self.spinBox.valueChanged.connect(self.tt)
        self.btn1.clicked.connect(self.off)
        self.modalBtn.clicked.connect(self.tta)
        self.reg.clicked.connect(self.time_add)
        self.time.returnPressed.connect(self.time_add)
        self.savBtn.pressed.connect(self.save)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Time Shower"))
        self.btn1.setText(_translate("MainWindow", "퇴근!"))
        self.lbl1.setText(_translate("MainWindow", "원생명:"))
        self.reg.setText(_translate("MainWindow", "등록"))
        self.lbl2.setText(_translate("MainWindow", "시간: "))
        self.savBtn.setText(_translate("MainWindow", "파일로 저장"))
        self.modalBtn.setText(_translate("MainWindow", "모달 창 띄우기"))

    def tt(self):
        self.dialog.setFixedWidth(self.spinBox.value())

    def tta(self):
        self.center()
        self.dialog.show()

    def save(self):
        save_name = QtWidgets.QFileDialog.getSaveFileName(None, '저장할 파일을 선택해주세요.', '', "CSV(엑셀) 파일 (*.csv)")[0]
        f = open(save_name, "w")
        f.write(self.t)
        f.close()


    def off(self):
        self.dialog.close()
        self.MW.close()

    def center(self):
        frame_info = self.dialog.frameGeometry()
        frame_info.moveCenter(QtCore.QPoint(round(1920 - self.spinBox.value() / 2), 540))
        self.dialog.move(frame_info.topLeft())

    def time_add(self):
        self.dialog.close()
        lbl = QtWidgets.QLabel(self.dialog)
        lbl.setFont(self.font1)
        lbl.setGeometry(QtCore.QRect(20 if len(self.times) < 13 else 220,
                                     10 + 60 * (len(self.times) - 0 if len(self.times) < 13 else len(self.times) - 13),
                                     171, 41))
        if self.time.text() == "":
            t = f"{self.name.text()} - {datetime.now().strftime('%H:%M')}"
        else:
            t = f"{self.name.text()} - {self.time.text()[:2] + ':' + self.time.text()[2:]}"
        self.t += t.replace(" - ", ",") + "\n"
        self.model.appendRow(QtGui.QStandardItem(t))
        self.timeview.setModel(self.model)
        lbl.setText(t)
        self.times.append(lbl)
        self.dialog.update()
        self.name.setText("")
        self.time.setText("")
        self.dialog.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
